SET NOCOUNT ON;
DECLARE @NewId INT;
EXEC dbo.sp_RegistrarUsuario @NombreUsuario=N'cajero', @Correo=N'cajero.demo@example.invalid', @Password=N'Test_Roles_2026!', @NombreCompleto=N'Cajero DEMO', @UsuarioId=@NewId OUTPUT;
EXEC dbo.sp_RegistrarUsuario @NombreUsuario=N'auditor', @Correo=N'auditor.demo@example.invalid', @Password=N'Test_Roles_2026!', @NombreCompleto=N'Auditor DEMO', @UsuarioId=@NewId OUTPUT;
DECLARE @Admin INT = (SELECT UsuarioId FROM dbo.Usuario WHERE NombreUsuario = N'admin');
DECLARE @Cajero INT = (SELECT UsuarioId FROM dbo.Usuario WHERE NombreUsuario = N'cajero');
DECLARE @Auditor INT = (SELECT UsuarioId FROM dbo.Usuario WHERE NombreUsuario = N'auditor');
DECLARE @AdminRol INT = (SELECT RolId FROM dbo.Rol WHERE Nombre = N'Administrador');
DECLARE @CajeroRol INT = (SELECT RolId FROM dbo.Rol WHERE Nombre = N'Cajero');
DECLARE @AuditorRol INT = (SELECT RolId FROM dbo.Rol WHERE Nombre = N'Auditor');
INSERT dbo.Usuario_Rol VALUES (@Cajero, @CajeroRol, SYSUTCDATETIME()), (@Auditor, @AuditorRol, SYSUTCDATETIME());
DECLARE @Roles dbo.TipoRolUsuario;
DECLARE @Usuarios TABLE (UsuarioId INT, NombreUsuario NVARCHAR(50), NombreCompleto NVARCHAR(150), Correo NVARCHAR(254), Activo BIT, Roles NVARCHAR(MAX));
INSERT @Usuarios EXEC dbo.sp_ListarUsuariosAdministracion;
IF NOT EXISTS (SELECT 1 FROM @Usuarios WHERE UsuarioId = @Cajero AND Roles = N'Cajero') THROW 53100, 'Listado incorrecto.', 1;
INSERT @Roles VALUES (@CajeroRol);
EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin;
DELETE @Roles; INSERT @Roles VALUES (@AuditorRol);
EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin;
IF EXISTS (SELECT 1 FROM dbo.Usuario_Rol WHERE UsuarioId=@Cajero AND RolId=@CajeroRol) THROW 53100, 'No se quito el rol.', 1;
INSERT @Roles VALUES (@CajeroRol);
EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin;
EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin;
IF (SELECT COUNT(*) FROM dbo.Usuario_Rol WHERE UsuarioId=@Cajero) <> 2 THROW 53100, 'Asignacion multiple o idempotencia incorrecta.', 1;
INSERT @Roles VALUES (@CajeroRol);
BEGIN TRY EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin; THROW 53100, 'Acepto duplicados.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53002 THROW; END CATCH;
DELETE @Roles; INSERT @Roles VALUES (2147483647);
BEGIN TRY EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin; THROW 53100, 'Acepto rol inexistente.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53002 THROW; END CATCH;
DELETE @Roles; INSERT @Roles VALUES (@CajeroRol);
BEGIN TRY EXEC dbo.sp_ActualizarRolesUsuario 2147483647, @Roles, @Admin; THROW 53100, 'Acepto usuario inexistente.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53001 THROW; END CATCH;
BEGIN TRY EXEC dbo.sp_ObtenerRolesUsuario 2147483647; THROW 53100, 'Consulta acepto usuario inexistente.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53001 THROW; END CATCH;
UPDATE dbo.Rol SET Activo = 0 WHERE RolId = @AuditorRol;
DECLARE @Activos TABLE (RolId INT, Nombre NVARCHAR(50), Descripcion NVARCHAR(250));
INSERT @Activos EXEC dbo.sp_ListarRolesActivos;
IF EXISTS (SELECT 1 FROM @Activos WHERE RolId=@AuditorRol) THROW 53100, 'Lista incluyo rol inactivo.', 1;
DELETE @Roles; INSERT @Roles VALUES (@AuditorRol);
BEGIN TRY EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin; THROW 53100, 'Acepto rol inactivo.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53002 THROW; END CATCH;
UPDATE dbo.Rol SET Activo = 1 WHERE RolId = @AuditorRol;
IF (SELECT COUNT(*) FROM dbo.Usuario_Rol WHERE UsuarioId=@Cajero) <> 2 THROW 53100, 'Rollback incorrecto.', 1;
DELETE @Roles;
BEGIN TRY EXEC dbo.sp_ActualizarRolesUsuario @Admin, @Roles, @Admin; THROW 53100, 'Quito ultimo administrador.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53003 THROW; END CATCH;
BEGIN TRY EXEC dbo.sp_ActualizarRolesUsuario @Admin, @Roles, @Auditor; THROW 53100, 'Actor sin permiso aceptado.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53004 THROW; END CATCH;
UPDATE dbo.Usuario SET Activo = 0 WHERE UsuarioId=@Cajero;
INSERT @Roles VALUES (@AdminRol);
EXEC dbo.sp_ActualizarRolesUsuario @Cajero, @Roles, @Admin;
DELETE @Roles;
BEGIN TRY EXEC dbo.sp_ActualizarRolesUsuario @Admin, @Roles, @Admin; THROW 53100, 'Conto administrador inactivo.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 53003 THROW; END CATCH;
UPDATE dbo.Usuario SET Activo = 1 WHERE UsuarioId=@Cajero;
EXEC dbo.sp_ActualizarRolesUsuario @Admin, @Roles, @Cajero;
IF EXISTS (SELECT 1 FROM dbo.Usuario_Rol WHERE UsuarioId=@Admin AND RolId=@AdminRol) THROW 53100, 'No permitio quitar con segundo administrador.', 1;
IF NOT EXISTS (SELECT 1 FROM dbo.Bitacora_Transacciones WHERE TablaAfectada=N'Usuario_Rol' AND IdentificadorRegistro LIKE N'%ActorUsuarioId=%') THROW 53100, 'Falta auditoria.', 1;
IF EXISTS (SELECT 1 FROM dbo.Bitacora_Transacciones WHERE TablaAfectada=N'Usuario_Rol' AND (ValorAnterior LIKE N'%Password%' OR ValorNuevo LIKE N'%Salt%')) THROW 53100, 'Auditoria contiene secretos.', 1;
-- Una cuenta de base de datos limitada replica las concesiones del modulo sin usar el login real.
CREATE USER [user_roles_test_app] WITHOUT LOGIN;
GRANT EXECUTE ON OBJECT::dbo.sp_ListarUsuariosAdministracion TO [user_roles_test_app];
GRANT EXECUTE ON OBJECT::dbo.sp_ListarRolesActivos TO [user_roles_test_app];
GRANT EXECUTE ON OBJECT::dbo.sp_ObtenerRolesUsuario TO [user_roles_test_app];
GRANT EXECUTE ON OBJECT::dbo.sp_ActualizarRolesUsuario TO [user_roles_test_app];
GRANT EXECUTE, REFERENCES ON TYPE::dbo.TipoRolUsuario TO [user_roles_test_app];
EXECUTE AS USER = N'user_roles_test_app';
EXEC dbo.sp_ListarRolesActivos;
EXEC dbo.sp_ActualizarRolesUsuario @Auditor, @Roles, @Cajero;
BEGIN TRY SELECT UsuarioId FROM dbo.Usuario; THROW 53100, 'Permite SELECT directo.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 229 THROW; END CATCH;
BEGIN TRY DELETE dbo.Usuario_Rol WHERE UsuarioId=@Auditor; THROW 53100, 'Permite DELETE directo.', 1;
END TRY BEGIN CATCH IF ERROR_NUMBER() <> 229 THROW; END CATCH;
REVERT;
PRINT 'OK: usuarios, roles activos, asignaciones, duplicados, rollback, ultimo administrador, auditoria y minimo privilegio.';
